services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: votacao
      APP_USER_PASSWORD: votacao
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
